version: '3.9'

services:
  db:
    image: postgres:15
    container_name: inventory_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: inventory
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: inventory_app
    restart: always
    ports:
      - '3000:3000'
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: inventory
      DB_USER: admin
      DB_PASS: admin123
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  db_data:
